// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockPulse.Infrastructure.Persistence;

#nullable disable

namespace StockPulse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StockPulseDbContext))]
    [Migration("20260718153851_InitialStockPulse")]
    partial class InitialStockPulse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockPulse.Domain.Entities.NewsSource", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NewsSources");
                });

            modelBuilder.Entity("StockPulse.Domain.Entities.StockNews", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalUrl")
                        .HasColumnType("text");

                    b.Property<string>("DedupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ImpactScore")
                        .HasColumnType("numeric");

                    b.Property<string>("ProviderNewsKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sentiment")
                        .HasColumnType("integer");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("numeric");

                    b.Property<short>("SourceId")
                        .HasColumnType("smallint");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DedupHash")
                        .IsUnique();

                    b.HasIndex("ImpactScore")
                        .IsDescending();

                    b.HasIndex("PublishedAtUtc")
                        .IsDescending();

                    b.HasIndex("SourceId");

                    b.ToTable("stock_news", (string)null);
                });

            modelBuilder.Entity("StockPulse.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Market")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("watchlists", (string)null);
                });

            modelBuilder.Entity("StockPulse.Domain.Entities.StockNews", b =>
                {
                    b.HasOne("StockPulse.Domain.Entities.NewsSource", "Source")
                        .WithMany("News")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("StockPulse.Domain.Entities.StockNewsTicker", "Tickers", b1 =>
                        {
                            b1.Property<long>("NewsId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ticker")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<decimal>("ConfidenceScore")
                                .HasColumnType("numeric");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.HasKey("NewsId", "Ticker");

                            b1.HasIndex("Ticker", "NewsId")
                                .IsDescending(false, true);

                            b1.ToTable("stock_news_tickers", (string)null);

                            b1.WithOwner("News")
                                .HasForeignKey("NewsId");

                            b1.Navigation("News");
                        });

                    b.Navigation("Source");

                    b.Navigation("Tickers");
                });

            modelBuilder.Entity("StockPulse.Domain.Entities.NewsSource", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
